src/Entity/Comments.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentsRepository")
 */
class Comments
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $Content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $addedAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Articles", inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Article;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getAddedAt(): ?\DateTimeInterface
    {
        return $this->addedAt;
    }

    public function setAddedAt(\DateTimeInterface $addedAt): self
    {
        $this->addedAt = $addedAt;

        return $this;
    }

    public function getArticle(): ?Articles
    {
        return $this->Article;
    }

    public function setArticle(?Articles $Article): self
    {
        $this->Article = $Article;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Entity/Tag.php
<?php

namespace App\Entity;

use App\Repository\TagRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TagRepository::class)
 */
class Tag
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=300)
     */
    private $name;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, mappedBy="tags")
     */
    private $categories;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addTag($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->removeElement($category)) {
            $category->removeTag($this);
        }

        return $this;
    }
}

src/Form/TagType.php
<?php

namespace App\Form;

use App\Entity\Tag;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TagType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $name = $options['tagName'] ?? "";

        $builder
            ->add('name', TextType::class, [
                'label' => 'Tag name',
                'attr' => [
                    'value' => $name,
                ],
            ])
            ->add('submit', SubmitType::class, [
                'label' => $name == "" ? 'Submit new tag' : "Save tag changes",
                'attr' => [
                    'class' => 'form-btn',
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tag::class,
        ]);
        $resolver->setRequired("tagName");
    }

    public function getBlockPrefix()
    {
        return 'newTag';
    }
}

src/Controller/TagController.php
<?php

namespace App\Controller;

use App\Form\TagType;
use App\Repository\TagRepository;
use App\Services\DataServices;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\NoResultException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/tags")
 */
class TagController extends AbstractController
{
    private $entityManager;
    private $tagRepository;

    public function __construct(EntityManagerInterface $entityManager, TagRepository $tagRepository)
    {
        $this->entityManager = $entityManager;
        $this->tagRepository = $tagRepository;
    }

    /**
     * @Route("/", name="tagList")
     */
    function list(): Response {
        return $this->render('tag/list.html.twig', [
            'location' => 'List of tags',
            'path' => 'Tags',
            'pathLink' => 'tagList',
        ]);
    }

    /**
     * @Route("/get")
     */
    public function apiGetTags(DataServices $dataServices)
    {
        $group = $dataServices->getGroupedByFirstLetter("tags");

        if (sizeof($group) == 0) {
            return $this->json("There is nothing to show", 404);
        }

        $outputTags = [];

        foreach ($group as $letter => $tags) {
            foreach ($tags as $tag) {
                $outputTags[$letter][] = ['id' => $tag->getId(), 'name' => $tag->getName()];
            }
        }

        return $this->json($outputTags);
    }

    /**
     * @Route("/create", name="tagCreate")
     */
    public function create(?string $error = null, Request $request): Response
    {
        if (!in_array("ROLE_ADMIN", $this->getUser()->getRoles())) {
            return $this->redirectToRoute('home');
        }

        $form = $this->createForm(TagType::class, null, ['tagName' => null]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $tag = $form->getData();

            if (!$this->tagRepository->findOneBy(['name' => $tag->getName()])) {
                $this->entityManager->persist($tag);
                $this->entityManager->flush();

                return $this->redirectToRoute('tagList');
            } else {
                $error = "Such tag already exists";
            }
        }

        return $this->render('tag/create.html.twig', [
            'location' => 'Create tag',
            'path' => 'Tags',
            'pathLink' => 'tagList',
            'form' => $form->createView(),
            'error' => $error,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="tagEdit")
     */
    public function edit(int $id, ?string $error = null, Request $request): Response
    {
        if (!in_array("ROLE_ADMIN", $this->getUser()->getRoles())) {
            return $this->redirectToRoute('home');
        }
        $currentTag = $this->tagRepository->findOneBy(['id' => $id]);

        if (!$currentTag) {
            throw new NoResultException("No result was found to fulfill form requirements");
        }

        $form = $this->createForm(TagType::class, null, ['tagName' => $currentTag->getName()]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $newName = $form->getData()->getName();
            $existsTagWithNewName = $this->tagRepository->findOneBy(['name' => $newName]) ? true : false;

            if (!$existsTagWithNewName) {
                $currentTag->setName($newName);
                $this->entityManager->flush();

                return $this->redirectToRoute('tagList');
            } else {
                $error = "Such tag already exists";
            }
        }

        return $this->render('tag/edit.html.twig', [
            'location' => 'Edit tag',
            'path' => 'Tags',
            'pathLink' => 'tagList',
            'form' => $form->createView(),
            'error' => $error,
            'currentName' => $currentTag->getName(),
        ]);
    }
}

templates/tag/create.html.twig
{% extends "defaults/_nav.html.twig" %}

{% block stylesheets %}
	{{ parent() }}
	<link rel="stylesheet" href="/styles/app/tags/form.css">
{% endblock %}

{% block content %}
	{{ form_start(form) }}
	<div class="form-box">
		{{ form_label(form.name) }}
		{{ form_widget(form.name) }}
	</div>
	{{ form_widget(form.submit) }}
	{% if error %}
		<div class="alert-danger">{{ error }}</div>
	{% endif %}
	{{ form_end(form) }}
{% endblock %}

{% block create %}
	{% if app.user and "ROLE_ADMIN" in app.user.roles %}
		<div class="admin-create-btn disabled">
			<svg class="plus-icon" stroke="currentColor" fill="currentColor" stroke-width="0" viewbox="0 0 16 16" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
				<path fill-rule="evenodd" d="M8 3.5a.5.5 0 01.5.5v4a.5.5 0 01-.5.5H4a.5.5 0 010-1h3.5V4a.5.5 0 01.5-.5z" clip-rule="evenodd"></path>
				<path fill-rule="evenodd" d="M7.5 8a.5.5 0 01.5-.5h4a.5.5 0 010 1H8.5V12a.5.5 0 01-1 0V8z" clip-rule="evenodd"></path>
			</svg>
			Create new tag
		</div>
	{% endif %}
{% endblock %}

templates/tag/edit.html.twig
{% extends "defaults/_nav.html.twig" %}

{% block stylesheets %}
	{{ parent() }}
	<link rel="stylesheet" href="/styles/app/tags/form.css">
{% endblock %}

{% block content %}
	{{ form_start(form) }}
	<div class="form-box">
		{{ form_label(form.name) }}
		{{ form_widget(form.name) }}
	</div>
	{{ form_widget(form.submit) }}
	{% if error %}
		<div class="alert-danger">{{ error }}</div>
	{% endif %}
	{{ form_end(form) }}
{% endblock %}

{% block sideBtn %}
	{% if app.user and "ROLE_ADMIN" in app.user.roles %}
		<a href="{{ path('tagCreate') }}" class="admin-create-btn">
			<svg class="plus-icon" stroke="currentColor" fill="currentColor" stroke-width="0" viewbox="0 0 16 16" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
				<path fill-rule="evenodd" d="M8 3.5a.5.5 0 01.5.5v4a.5.5 0 01-.5.5H4a.5.5 0 010-1h3.5V4a.5.5 0 01.5-.5z" clip-rule="evenodd"></path>
				<path fill-rule="evenodd" d="M7.5 8a.5.5 0 01.5-.5h4a.5.5 0 010 1H8.5V12a.5.5 0 01-1 0V8z" clip-rule="evenodd"></path>
			</svg>
			Create new tag
		</a>
	{% endif %}
{% endblock %}

templates/tag/list.html.twig
{% extends "defaults/_nav.html.twig" %}

{% block stylesheets %}
	{{ parent() }}
	<link rel="stylesheet" href="/styles/app/tags/list.css">
{% endblock %}

{% block content %}
	<section class="tags-list">
		<svg class='loading-icon' stroke="currentColor" fill="currentColor" stroke-width="0" viewbox="0 0 16 16" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
			<path fill-rule="evenodd" d="M4.5 3a2.5 2.5 0 015 0v9a1.5 1.5 0 01-3 0V5a.5.5 0 011 0v7a.5.5 0 001 0V3a1.5 1.5 0 10-3 0v9a2.5 2.5 0 005 0V5a.5.5 0 011 0v7a3.5 3.5 0 11-7 0V3z" clip-rule="evenodd"></path>
		</svg>
		<p class="loading-text">Getting data to show</p>
	</section>
{% endblock %}

{% block sideBtn %}
	{% if app.user and "ROLE_ADMIN" in app.user.roles %}
		<a href="{{ path('tagCreate') }}" class="admin-create-btn">
			<svg class="plus-icon" stroke="currentColor" fill="currentColor" stroke-width="0" viewbox="0 0 16 16" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
				<path fill-rule="evenodd" d="M8 3.5a.5.5 0 01.5.5v4a.5.5 0 01-.5.5H4a.5.5 0 010-1h3.5V4a.5.5 0 01.5-.5z" clip-rule="evenodd"></path>
				<path fill-rule="evenodd" d="M7.5 8a.5.5 0 01.5-.5h4a.5.5 0 010 1H8.5V12a.5.5 0 01-1 0V8z" clip-rule="evenodd"></path>
			</svg>
			Create new tag
		</a>
	{% endif %}
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	<script src="/scripts/tag.js"></script>
{% endblock %}